name: wgpu_ffi
description: Experimental WGPU Dart FFI bindings.
version: 0.0.0
homepage: https://github.com/jpnurmi/dart_wgpu_ffi
repository: https://github.com/jpnurmi/dart_wgpu_ffi
issue_tracker: https://github.com/jpnurmi/dart_wgpu_ffi/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  dylib: ^0.2.0-nullsafety.0
  ffi: ^0.2.0-nullsafety.1
  pedantic: ^1.10.0-nullsafety.3

dev_dependencies:
  ffigen: ^2.0.0-dev.2
  test: ^1.16.0-nullsafety.13
